parameters:
  disable_sigin: no
  
  site:
    name:                      'Kryptos'
    url:                       'www.kryptos.com'
    email_activate_from:       'activations@kryptos.com'
    email_activate_fromname:   'Kryptos'
  
  
  mongo_connection:
    server:           'mongodb://localhost:27017'
    options:          ''
    default_db:       'kryptos'


  session_memcache_host:               127.0.0.1
  session_memcache_port:               11211
  session_memcache_prefix:             sess_
  session_memcache_expire:             1200
  
  purchase_conversions:
    # conversionRate is the amount that each conversion costs in pence (or other currency). a value of less than 1 means each is less than 1p
    conversion_rate: 3
    # a vat_rate as percentage, range from [0 - 100]
    vat_rate: 20
    