parameters:
  disable_sigin: no
  
  
  mongo_connection:
    server:           'mongodb://localhost:27017'
    options:          ''
    default_db:       'kryptos'


  session_memcache_host:               127.0.0.1
  session_memcache_port:               11211
  session_memcache_prefix:             sess_
  session_memcache_expire:             1200