parameters:
  disable_sigin: no
  
  site:
    name:                      'Kryptos'
    url:                       'kryptos.nitin.me.uk'
    email_activate_from:       'activations@kryptos.com'
    email_activate_fromname:   'Kryptos'
    tmp_path:                  '/var/www/vhosts/kryptos.com/tmp/'
  
  mongo_connection:
    server:           'mongodb://localhost:27017'
    options:          ''
    default_db:       'kryptos'


  session_memcache_host:               127.0.0.1
  session_memcache_port:               11211
  session_memcache_prefix:             sess_
  session_memcache_expire:             1200
  
  purchase_conversions:
    # conversionRate is the amount that each conversion costs in pounds (or other currency). a value of less than 1 means each is less than 1 pound
    # rate of 1 means 1 pound gets you 1 conversion; rate of 0.5 means 1 pound gets you 2 conversions; rate of 2 means 2 pounds gets you 1 conversion;
    conversion_rate: 0.5
    # a vat_rate as percentage, range from [0 - 100]
    vat_rate: 20
    
  credits:  0    # the number of conversions that all users start on, when signin enabled


  sagepay:
    PaymentUrl:              https://test.sagepay.com/Simulator/VSPServerGateway.asp?Service=VendorRegisterTx
    VPSProtocol:             2.23   
    Vendor:                  kryptos
    Currency:                GBP
    CurrencySymbol:          '&pound;'
    Description:             Conversions purchase
    NotificationURL:         sage_notification_page 
    error_payment_register:  'Ooops!, the system has been unable to contact our payment provider. Please try again. If you continue to experience this problem please give us a call.'
    RedirectURLPass:         sage_redirect_pass
    RedirectURLFail:         sage_redirect_fail
    
  batch_convert:
    # 5 mins - used by each job that reads the queue - if we are uploading files and reading contents to mongodb 
    #locktime: 300
    # locktime: 630
    locktime: 15
    ready_location:          'batch/ready/'
    converted_location:      'batch/converted/'
    processed_location:      'batch/processed/'
    stats_location:          'batch/stats/'

  bankwizard:
    #batch_command:           'java --cp /var/www/bankwizard/FileScanningUtilityFinalV1.jar:bwint10.jar DataScanMain.Datascan "%s" "%s" "%s"'
    batch_command:           'java --cp /var/www/bankwizard/FileScanningUtilityFinalV1.jar:/var/www/bankwizard/bwint10.jar DataScanMain.Datascan "%s" "%s" "%s"'