Kryptos\SageBundle\Entity\PaymentBilling:
    properties:
        billingSurname:
            - NotBlank:
                message: msg_title_billing_details_incomplete|msg_desc_enter_surname
        billingFirstnames:
            - NotBlank:
                message: msg_title_billing_details_incomplete|msg_desc_enter_firstname
        billingAddress1:
            - NotBlank:
                message: msg_title_billing_details_incomplete|msg_desc_enter_address_1
        billingAddress2:
            - NotBlank:  
                message: msg_title_billing_details_incomplete|msg_desc_enter_address_2
        billingCity:
            - NotBlank:
                message: msg_title_billing_details_incomplete|msg_desc_enter_city
        billingPostCode:
            - NotBlank: 
                message: msg_title_billing_details_incomplete|msg_desc_enter_postcode
        billingCountry:
            - NotBlank: 
                message: msg_title_billing_details_incomplete|msg_desc_enter_country
        acceptTerms:
            - NotBlank: 
                message: msg_title_billing_details_incomplete|msg_desc_accept_terms