homepage:
    pattern:  /
    defaults: { _controller: KryptosKryptosBundle:Default:index }
    
signin:
    pattern:  /signin
    defaults: { _controller: KryptosKryptosBundle:Default:signin }
    
register:
    pattern:  /register
    defaults: { _controller: KryptosKryptosBundle:Default:register }
    
register_submitted:
    pattern:  /register/success
    defaults: { _controller: KryptosKryptosBundle:Default:registerSubmitted }

register_activate:
    pattern:  /register/activate/{userId}/{code1}/{code2}
    defaults: { _controller: KryptosKryptosBundle:Default:registerActivate, userId: null, code1: null, code2: null  }
    
logout:
    pattern:  /logout
    defaults: { _controller: KryptosKryptosBundle:Default:logout }

welcome:
    pattern:  /welcome
    defaults: { _controller: KryptosKryptosBundle:Default:welcome }
    
    
password_reset_email:
    pattern:  /password/reset
    defaults: { _controller: KryptosKryptosBundle:Default:resetPasswordEmail }

password_reset_email_submitted:
    pattern:  //password/reset/success
    defaults: { _controller: KryptosKryptosBundle:Default:resetPasswordEmailSubmitted }

password_reset_question_success:
    pattern:  //password/reset/question/success
    defaults: { _controller: KryptosKryptosBundle:Default:resetPasswordQuestionSuccess }
    
password_reset_question:
    pattern:  /password/reset/question/{userId}/{code1}/{code2}
    defaults: { _controller: KryptosKryptosBundle:Default:resetPasswordQuestion, userId: null, code1: null, code2: null }
    
    
purchase_conversions:
    pattern:  /purchase/conversions
    defaults: { _controller: KryptosKryptosBundle:PurchaseConversions:index }
    
purchase_conversions_calc_rate:
    pattern:  /purchase/conversions/calculate/rates/{conversionAmount}
    defaults: { _controller: KryptosKryptosBundle:PurchaseConversions:calculateRate }


convert_batch:
    pattern:  /convert/batch
    defaults: { _controller: KryptosKryptosBundle:ConvertBatch:index }
    
convert_batch_template:
    pattern:  /convert/batch/template
    defaults: { _controller: KryptosKryptosBundle:ConvertBatch:template }

convert_batch_download:
    pattern:  /convert/batch/download/{fileId}
    defaults: { _controller: KryptosKryptosBundle:ConvertBatch:download, fileId: null }

convert_single:
    pattern:  /convert/single
    defaults: { _controller: KryptosKryptosBundle:ConvertSingle:index }

api_details:
    pattern:  /api_details
    defaults: { _controller: KryptosKryptosBundle:Api:details }


file_status_ajax:
    pattern:  /file/status/ajax
    defaults: { _controller: KryptosKryptosBundle:FileStatus:index }


account_summary:
    pattern:  /account/summary
    defaults: { _controller: KryptosKryptosBundle:Account:summary }

account_balance:
    pattern:  /account/balance
    defaults: { _controller: KryptosKryptosBundle:Account:balance }

account_history:
    pattern:  /account/history
    defaults: { _controller: KryptosKryptosBundle:Account:history }

account_settings:
    pattern:  /account/settings
    defaults: { _controller: KryptosKryptosBundle:Account:settings }

download_help_prepare_file:
    pattern:  /download/help_prepare_file
    defaults: { _controller: KryptosKryptosBundle:Download:helpPrepareFile }

download_help_upload_file:
    pattern:  /download/help_upload_file
    defaults: { _controller: KryptosKryptosBundle:Download:helpUploadFile }
    
    
locale_switch:
    pattern:  /locale/switch/{_locale}
    defaults: { _controller: KryptosKryptosBundle:Locale:switch, _locale: en}
    requirements:
        _locale: en|de|fr|sp|it