homepage:
    pattern:  /
    defaults: { _controller: KryptosKryptosBundle:Default:index }
    
signin:
    pattern:  /signin
    defaults: { _controller: KryptosKryptosBundle:Default:signin }
    
register:
    pattern:  /register
    defaults: { _controller: KryptosKryptosBundle:Default:register }
    
register_submitted:
    pattern:  /register/success
    defaults: { _controller: KryptosKryptosBundle:Default:registerSubmitted }

register_activate:
    pattern:  /register/activate/{userId}/{code1}/{code2}
    defaults: { _controller: KryptosKryptosBundle:Default:registerActivate, userId: null, code1: null, code2: null  }
    
logout:
    pattern:  /logout
    defaults: { _controller: KryptosKryptosBundle:Default:logout }

welcome:
    pattern:  /welcome
    defaults: { _controller: KryptosKryptosBundle:Default:welcome }
    
password_reset_email:
    pattern:  /welcome
    defaults: { _controller: KryptosKryptosBundle:Default:resetPasswordEmail }
    
password_reset_question:
    pattern:  /welcome
    defaults: { _controller: KryptosKryptosBundle:Default:resetPasswordQuestion }
    
    
purchase_conversions:
    pattern:  /purchase/conversions
    defaults: { _controller: KryptosKryptosBundle:PurchaseConversions:index }
    
purchase_conversions_calc_rate:
    pattern:  /purchase/conversions/calculate/rates/{conversionAmount}
    defaults: { _controller: KryptosKryptosBundle:PurchaseConversions:calculateRate }


convert_batch:
    pattern:  /convert/batch
    defaults: { _controller: KryptosKryptosBundle:ConvertBatch:index }

convert_single:
    pattern:  /convert/single
    defaults: { _controller: KryptosKryptosBundle:ConvertBatch:index }


file_status_ajax:
    pattern:  /file/status/ajax
    defaults: { _controller: KryptosKryptosBundle:FileStatus:index }