homepage:
    pattern:  /
    defaults: { _controller: KryptosKryptosBundle:Default:index }
    
signin:
    pattern:  /signin
    defaults: { _controller: KryptosKryptosBundle:Default:signin }
    
register:
    pattern:  /register
    defaults: { _controller: KryptosKryptosBundle:Default:register }
    
register_success:
    pattern:  /register/success
    defaults: { _controller: KryptosKryptosBundle:Default:registerSuccess }
