parameters:
#    kryptos_kryptos.example.class: Kryptos\KryptosBundle\Example

    config_manager.class:                Kryptos\KryptosBundle\Services\ConfigManager
    mongo_connection.class:              Kryptos\KryptosBundle\Services\MongoConnection
    conversion_calculator.class:         Kryptos\KryptosBundle\Services\ConversionCalculator
    user_manager.class:                  Kryptos\KryptosBundle\Model\Manager\UserManager
    sage_notification_manager.class:     Kryptos\KryptosBundle\Model\Manager\SageNotificationManager
    file_manager.class:                  Kryptos\KryptosBundle\Model\Manager\FileManager
    file_error_manager.class:            Kryptos\KryptosBundle\Model\Manager\FileErrorManager
    bank_account_manager.class:          Kryptos\KryptosBundle\Model\Manager\BankAccountManager
    conversion_manager.class:            Kryptos\KryptosBundle\Model\Manager\ConversionManager
    unique_username_validator.class:     Kryptos\KryptosBundle\Validator\Constraints\UniqueUsernameValidator
    unique_email_validator.class:        Kryptos\KryptosBundle\Validator\Constraints\UniqueEmailValidator
    login_validator.class:               Kryptos\KryptosBundle\Lib\LoginValidator
    batch_insert_file.class:             Kryptos\KryptosBundle\Lib\BatchInsertFile
    batch_upload_file.class:             Kryptos\KryptosBundle\Lib\BatchUploadFile
    single_conversion.class:             Kryptos\KryptosBundle\Lib\SingleConversion


services:
#    kryptos_kryptos.example:
#        class: %kryptos_kryptos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    config_manager:
        class:          %config_manager.class%
        arguments:      [@service_container]

    mongo_connection:
        class:          %mongo_connection.class%
        arguments:      [@service_container]
        
    conversion_calculator:
        class:          %conversion_calculator.class%
        arguments:      [@config_manager]
        
    user_manager:
        class:          %user_manager.class%
        arguments:      [@mongo_connection, @conversion_calculator, @conversion_manager]
     
    sage_notification_manager:
        class:          %sage_notification_manager.class%
        arguments:      [@mongo_connection]

    file_manager:
        class:          %file_manager.class%
        arguments:      [@mongo_connection]

    file_error_manager:
        class:          %file_error_manager.class%
        arguments:      [@mongo_connection]

    bank_account_manager:
        class:          %bank_account_manager.class%
        arguments:      [@mongo_connection]
        
    conversion_manager:
        class:          %conversion_manager.class%
        arguments:      [@mongo_connection]


    unique_username_validator:
        class:          %unique_username_validator.class%
        arguments:      [@user_manager, @config_manager]
        tags:
            - { name: validator.constraint_validator, alias: UniqueUsernameValidator }
    
    unique_email_validator:
        class:          %unique_email_validator.class%
        arguments:      [@user_manager]
        tags:
            - { name: validator.constraint_validator, alias: UniqueEmailValidator }
    
    
    # http://hipaway.com/blog/symfony2-sessions-in-memcache/
    session.memcache:
        class: Memcache
        calls:
          - [ addServer, [ %session_memcache_host%, %session_memcache_port% ]]

    session.handler.memcache:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcacheSessionHandler
        arguments: [ @session.memcache, { prefix: %session_memcache_prefix%, expiretime: %session_memcache_expire% } ]
    
    login_validator:
        class:          %login_validator.class%
        arguments:      [@session.handler.memcache, @session, %session_memcache_expire%]

    batch_insert_file:
        class:          %batch_insert_file.class%
        arguments:      [@config_manager, @file_manager, @bank_account_manager, @file_error_manager]

    batch_upload_file:
        class:          %batch_upload_file.class%
        arguments:      [@config_manager, @file_manager, @bank_account_manager, @file_error_manager, @user_manager]
        
    single_conversion:
        class:          %single_conversion.class%
        arguments:      [@config_manager]
        