Kryptos\KryptosBundle\Entity\Register:
    properties:
        username:
            - NotBlank: ~
            - Kryptos\KryptosBundle\Validator\Constraints\UniqueUsername: ~
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        jobTitle:
            - NotBlank: ~
        company:
            - NotBlank: ~
        location:
            - NotBlank: ~
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
            - Kryptos\KryptosBundle\Validator\Constraints\UniqueEmail: ~
        password:
            - NotBlank: ~