Kryptos\KryptosBundle\Entity\Register:
    properties:
        title:
            - NotBlank:
                message: msg_title_registration_incomplete|msg_desc_select_title
        firstName:
            - NotBlank:
                message: msg_title_registration_incomplete|msg_desc_enter_forename
        lastName:
            - NotBlank:
                message: msg_title_registration_incomplete|msg_desc_enter_surname
        jobTitle:
            - NotBlank:  
                message: msg_title_registration_incomplete|msg_desc_enter_job_title
        company:
            - NotBlank:
                message: msg_title_registration_incomplete|msg_desc_enter_company_name
        location:
            - NotBlank: 
                message: msg_title_registration_incomplete|msg_desc_enter_location
        email:
            - Email:
                message: msg_title_incorrect_email|msg_desc_incorrect_email_try_again
                checkMX: true
            - Kryptos\KryptosBundle\Validator\Constraints\UniqueEmail: 
                message: msg_title_email_already_registered|msg_desc_email_already_registered
        password:
            - NotBlank: 
                message: msg_title_registration_incomplete|msg_desc_enter_password
        acceptTerms:
            - "True":
                message: msg_title_registration_incomplete|msg_desc_accept_terms


Kryptos\KryptosBundle\Entity\SettingsUserDetails:
    properties:
        title:
            - NotBlank:
                message: msg_title_user_details_imcomplete|msg_desc_select_title
        firstName:
            - NotBlank:
                message: msg_title_user_details_imcomplete|msg_desc_enter_forename
        lastName:
            - NotBlank:
                message: msg_title_user_details_imcomplete|msg_desc_enter_surname
        jobTitle:
            - NotBlank:  
                message: msg_title_user_details_imcomplete|msg_desc_enter_job_title
        company:
            - NotBlank:
                message: msg_title_user_details_imcomplete|msg_desc_enter_company_name
        location:
            - NotBlank: 
                message: msg_title_user_details_imcomplete|msg_desc_enter_location
        email:
            - Email:
                message: msg_title_incorrect_email|msg_desc_incorrect_email_try_again
                checkMX: true


Kryptos\KryptosBundle\Entity\SettingsUserPassword:
    properties:
        oldPassword:
            - NotBlank: 
                message: msg_title_details_incomplete|msg_desc_enter_old_password.
        password:
            - NotBlank: 
                message: msg_title_details_incomplete|msg_desc_enter_new_password.


Kryptos\KryptosBundle\Entity\Signin:
    properties:
        email:
            - Email:
                message: msg_title_incorrect_email|msg_desc_incorrect_email
                checkMX: true
            - NotBlank:
                message: msg_title_login_incomplete|msg_desc_enter_email
        password:
            - NotBlank: 
                message: msg_title_login_incomplete|msg_desc_enter_password


Kryptos\KryptosBundle\Entity\ResetPasswordEmail:
    properties:
        email:
            - Email:
                message: msg_title_incorrect_email|msg_desc_incorrect_email
                checkMX: true
            - NotBlank: 
                message: msg_title_incorrect_email|msg_desc_enter_email

Kryptos\KryptosBundle\Entity\ResetPasswordQuestion:
    properties:
        password:
            - NotBlank: 
                message: msg_title_password_reset_incomplete|msg_desc_enter_password