Kryptos\KryptosBundle\Entity\Register:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        jobTitle:
            - NotBlank: ~
        company:
            - NotBlank: ~
        location:
            - NotBlank: ~
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true