Kryptos\KryptosBundle\Entity\Register:
    properties:
        firstName:
            - NotBlank:
                message: Registration incomplete|Please enter your forename.
        lastName:
            - NotBlank:
                message: Registration incomplete|Please enter your surname.
        jobTitle:
            - NotBlank:  
                message: Registration incomplete|Please enter your Job Title.
        company:
            - NotBlank:
                message: Registration incomplete|Please enter your company name.
        location:
            - NotBlank: 
                message: Registration incomplete|Please enter your location.
        email:
            - Email:
                message: Incorrect Email|The email "{{ value }}" is not a valid email|Please try again.
                checkMX: true
            - Kryptos\KryptosBundle\Validator\Constraints\UniqueEmail: ~
        password:
            - NotBlank: 
                message: Registration incomplete|Please enter your password.
        acceptTerms:
            - "True":
                message: Registration incomplete|You must accept the terms and conditions in order to proceed.


Kryptos\KryptosBundle\Entity\Signin:
    properties:
        email:
            - Email:
                message: Incorrect Email|The email "{{ value }}" is not a valid email.
                checkMX: true
            - NotBlank:
                message: Login incomplete|Please enter your email.
        password:
            - NotBlank: 
                message: Login incomplete|Please enter your password.


Kryptos\KryptosBundle\Entity\ResetPasswordEmail:
    properties:
        email:
            - Email:
                message: Incorrect Email|The email "{{ value }}" is not a valid email.
                checkMX: true
            - NotBlank: 
                message: Incorrect Email|Please enter your email.
