Kryptos\KryptosBundle\Entity\Register:
    properties:
        title:
            - NotBlank:
                message: Registration incomplete|Please select your title.
        firstName:
            - NotBlank:
                message: Registration incomplete|Please enter your forename.
        lastName:
            - NotBlank:
                message: Registration incomplete|Please enter your surname.
        jobTitle:
            - NotBlank:  
                message: Registration incomplete|Please enter your Job Title.
        company:
            - NotBlank:
                message: Registration incomplete|Please enter your company name.
        location:
            - NotBlank: 
                message: Registration incomplete|Please enter your location.
        email:
            - Email:
                message: Incorrect Email|The email "{{ value }}" is not a valid email address. Please try again.
                checkMX: true
            - Kryptos\KryptosBundle\Validator\Constraints\UniqueEmail: 
                message: Email already registered|The email "{{ value }}" already exists on our system. If you have previously registered and forgotten your password, please go back to the sign in screen and reset your password by clicking on 'Forgotten your password?'
        password:
            - NotBlank: 
                message: Registration incomplete|Please enter your password.
        acceptTerms:
            - "True":
                message: Registration incomplete|You must accept the terms and conditions in order to proceed.


Kryptos\KryptosBundle\Entity\SettingsUserDetails:
    properties:
        title:
            - NotBlank:
                message: User details incomplete|Please select your title.
        firstName:
            - NotBlank:
                message: User details incomplete|Please enter your forename.
        lastName:
            - NotBlank:
                message: User details incomplete|Please enter your surname.
        jobTitle:
            - NotBlank:  
                message: User details incomplete|Please enter your Job Title.
        company:
            - NotBlank:
                message: User details incomplete|Please enter your company name.
        location:
            - NotBlank: 
                message: User details incomplete|Please enter your location.
        email:
            - Email:
                message: Incorrect Email|The email "{{ value }}" is not a valid email address. Please try again.
                checkMX: true


Kryptos\KryptosBundle\Entity\SettingsUserPassword:
    properties:
        oldPassword:
            - NotBlank: 
                message: Details incomplete|Please enter your old password.
        password:
            - NotBlank: 
                message: Details incomplete|Please enter your new password.


Kryptos\KryptosBundle\Entity\Signin:
    properties:
        email:
            - Email:
                message: Incorrect Email|The email "{{ value }}" is not a valid email.
                checkMX: true
            - NotBlank:
                message: Login incomplete|Please enter your email.
        password:
            - NotBlank: 
                message: Login incomplete|Please enter your password.


Kryptos\KryptosBundle\Entity\ResetPasswordEmail:
    properties:
        email:
            - Email:
                message: Incorrect Email|The email "{{ value }}" is not a valid email.
                checkMX: true
            - NotBlank: 
                message: Incorrect Email|Please enter your email.

Kryptos\KryptosBundle\Entity\ResetPasswordQuestion:
    properties:
        password:
            - NotBlank: 
                message: Password reset incomplete|Please enter your password.